config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  get 'hello_world', to: 'hello_world#index'
  get 'hello_world', to: 'hello_world#index'
  get 'hello_world', to: 'hello_world#index'
  resources :coffee_boxes
  resources :buyers

  root    'home#home'
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  has_many :coffee_boxes

  validates :name,  presence: true,
                    length: { maximum: 30 },
                    uniqueness: { case_sensitive: false }

  attr_accessor :amount

  def amount
    self.amount = coffee_boxes.size
  end

  def fullData
    {
      id: id,
      name: name,
      coffee_boxes: coffee_boxes.map { |cb| { date: cb.date, buyer_id: cb.buyer_id } },
      created_at: created_at,
      updated_at: updated_at,
    }
  end
end

app/models/coffee_box.rb
class CoffeeBox < ActiveRecord::Base
  belongs_to :buyer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  after_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end

  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(buyer_params);
    @buyers = Buyer.all
    respond_to do |format|
      if @buyer.save
        format.html { redirect_to root_path, notice: @buyer.name + ' was added. More coffee is coming!' }
        format.json { render :json => {:status => :ok, :data => @buyer.fullData }}
      else
        format.html { render :edit }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1
  # PATCH/PUT /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer.destroy
    respond_to do |format|
      format.html { redirect_to buyers_url, notice: 'Buyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:name)
    end
end

app/controllers/coffee_boxes_controller.rb
class CoffeeBoxesController < ApplicationController
  before_action :set_coffee_box, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  after_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end

  # GET /coffee_boxes
  # GET /coffee_boxes.json
  def index
    @coffee_boxes = CoffeeBox.all
  end

  # GET /coffee_boxes/1
  # GET /coffee_boxes/1.json
  def show
  end

  # GET /coffee_boxes/new
  def new
    @coffee_box = CoffeeBox.new
  end

  # GET /coffee_boxes/1/edit
  def edit
  end

  # POST /coffee_boxes
  # POST /coffee_boxes.json
  def create
    @coffee_box = CoffeeBox.new(coffee_box_params)

    respond_to do |format|
      if @coffee_box.save
        format.html { redirect_to @coffee_box, notice: 'Coffee box was successfully created.' }
        format.json { render :show, status: :created, location: @coffee_box }
      else
        format.html { render :new }
        format.json { render json: @coffee_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffee_boxes/1
  # PATCH/PUT /coffee_boxes/1.json
  def update
    respond_to do |format|
      if @coffee_box.update(coffee_box_params)
        format.html { redirect_to @coffee_box, notice: 'Coffee box was successfully updated.' }
        format.json { render :show, status: :ok, location: @coffee_box }
      else
        format.html { render :edit }
        format.json { render json: @coffee_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffee_boxes/1
  # DELETE /coffee_boxes/1.json
  def destroy
    @coffee_box.destroy
    respond_to do |format|
      format.html { redirect_to coffee_boxes_url, notice: 'Coffee box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee_box
      @coffee_box = CoffeeBox.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coffee_box_params
      params.require(:coffee_box).permit(:date, :buyer_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    @buyers = Buyer.all.sort_by { |buyer|  - buyer.amount }.map(&:fullData)
    @buyer  = Buyer.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/coffee_boxes_helper.rb
module CoffeeBoxesHelper
end

app/views/buyers/_form.html.erb
<%= form_for(@buyer) do |f| %>
  <% if @buyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

      <ul>
      <% @buyer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buyers/edit.html.erb
<h1>Editing Buyer</h1>

<%= render 'form' %>

<%= link_to 'Show', @buyer %> |
<%= link_to 'Back', buyers_path %>

app/views/buyers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buyers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Coffee Boxes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buyers.each do |buyer| %>
      <tr>
        <td><%= buyer.name %></td>
        <td><%= buyer.coffee_boxes.size %></td>

        <td><%= link_to 'Show', buyer %></td>
        <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
        <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buyer', new_buyer_path %>

app/views/buyers/new.html.erb
<h1>New Buyer</h1>

<%= render 'form' %>

<%= link_to 'Back', buyers_path %>

app/views/buyers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @buyer.name %>
</p>

<%= link_to 'Edit', edit_buyer_path(@buyer) %> |
<%= link_to 'Back', buyers_path %>

app/views/coffee_boxes/_form.html.erb
<%= form_for(@coffee_box) do |f| %>
  <% if @coffee_box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coffee_box.errors.count, "error") %> prohibited this coffee_box from being saved:</h2>

      <ul>
      <% @coffee_box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :buyer_id %><br>
    <%= f.collection_select :buyer_id, Buyer.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coffee_boxes/edit.html.erb
<h1>Editing Coffee Box</h1>

<%= render 'form' %>

<%= link_to 'Show', @coffee_box %> |
<%= link_to 'Back', coffee_boxes_path %>

app/views/coffee_boxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coffee Boxes</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Buyer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coffee_boxes.each do |coffee_box| %>
      <tr>
        <td><%= coffee_box.date %></td>
        <td><%= coffee_box.buyer.name %></td>
        <td><%= link_to 'Show', coffee_box %></td>
        <td><%= link_to 'Edit', edit_coffee_box_path(coffee_box) %></td>
        <td><%= link_to 'Destroy', coffee_box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coffee box', new_coffee_box_path %>

app/views/coffee_boxes/new.html.erb
<h1>New Coffee Box</h1>

<%= render 'form' %>

<%= link_to 'Back', coffee_boxes_path %>

app/views/coffee_boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @coffee_box.date %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @coffee_box.buyer.name %>
</p>

<%= link_to 'Edit', edit_coffee_box_path(@coffee_box) %> |
<%= link_to 'Back', coffee_boxes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helpling Coffee Counter</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
 <%= react_component("CoffeeCounterApp",
      @buyers,
      generator_function: false,
      prerender: false,
      trace: true) %>
</body>
</html>